
public class Exception_Hanlding {

	public static void main(String[] args) {
		
		try {
		int data = 50/0;
		} catch (ArithmeticException e){
			System.out.println("Got Arithmetic exception");
		}	
		System.out.println("AFter code execution");
		

	}

}
