<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MVTL1076LT" name="Test" tests="4" failures="1" timestamp="27 Jan 2017 11:09:57 GMT" time="74.918" errors="0">
  <testcase name="AasserionsTest" time="27.827" classname="day_1.Session1">
    <failure type="java.lang.AssertionError" message="Iam done with Assertions expected [Demo Windows for practicing Selenium Automation1] but found [Demo Windows for practicing Selenium Automation]">
      <![CDATA[java.lang.AssertionError: Iam done with Assertions expected [Demo Windows for practicing Selenium Automation1] but found [Demo Windows for practicing Selenium Automation]
	at day_1.Session1.AasserionsTest(Session1.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- AasserionsTest -->
  <testcase name="facebook" time="42.518" classname="day_1.Session2"/>
  <testcase name="test2" time="28.435" classname="day_1.Session1"/>
  <testcase name="facebook1" time="32.335" classname="day_1.Session2"/>
</testsuite> <!-- Test -->
